#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

#./chemkin/Allrun

#rm dat*
#rm chem.bin
#rm logS*

#cp ./chemkin/chem.bin ./

#sprayFoam >log &
#mpirun -np 44 sprayFoam -parallel >log.sprayFoam &

spraySootTimeFoam >log.spraySootFoam 2>error.spraySootFoam &
#mpirun -np 44 spraySootTimeFoam -parallel >log.spraySootFoam 2>error.spraySootFoam &

# ----------------------------------------------------------------- end-of-file
