#!/bin/sh
#goldSmith
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

#killall sprayEngineKIVAFoam

chemkinToFoam -newFormat chem.inp new.therm foamchem.inp foamtherm.dat

gfortran ckinterp_.f

./a.out

# ----------------------------------------------------------------- end-of-file